INSERT INTO `tb_depart` VALUES (1, '计算机学院');
INSERT INTO `tb_depart` VALUES (3, '艺术设计学院');
INSERT INTO `tb_depart` VALUES (4, '自动化学院');
INSERT INTO `tb_depart` VALUES (5, '政法学院');
INSERT INTO `tb_depart` VALUES (7, '物理学院');
INSERT INTO `tb_depart` VALUES (8, '一生一世');
INSERT INTO `tb_depart` VALUES (9, '语言学院');
INSERT INTO `tb_depart` VALUES (10, '计算机学院');
INSERT INTO `tb_depart` VALUES (11, '计算机学院');
